enum ErrorCode {
  USERNAME_ALREADY_PRESENT,
  USERNAME_NOT_EXIST,
  USER_NOT_EXIST,
  USER_INSERTION_FAILED,
  INTERNAL_SERVER_ERROR,
  INVALID_PASSWORD,
  NOT_APLICABLE,
  ERROR_FETCHNG_DATA,
  INVALID_TOKEN,
  ROLE_NOT_EXIST,
  ROLE_INSERTION_FAILED,
  BAD_CONNECTION,
  GAME_NOT_FOUND,
  GAME_IS_NOT_ACTIVE,
  REQUEST_ALREADY_PROCESSING,
  REQUEST_NOT_FOUND,
}

export default ErrorCode;
