const ENV_KEYS = {
  SERVER_PORT: "SERVER_PORT",

  JWT_ACCESS_SECRET: "JWT_ACCESS_SECRET",
  JWT_REFRESH_SECRET: "JWT_REFRESH_SECRET",
  PASSWORD_SALT: "PASSWORD_SALT",

  DATABASE_DIALECT: "DATABASE_DIALECT",
  DATABASE_HOST: "DATABASE_HOST",
  DATABASE_PORT: "DATABASE_PORT",
  DATABASE_NAME: "DATABASE_NAME",

  DATABASE_USERNAME: "DATABASE_USERNAME",
  DATABASE_PASSWORD: "DATABASE_PASSWORD",
};

export default ENV_KEYS;
